// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Thesaurus API
#### RESTFUL THESAURUS API



    Schemes:
      http
    Host: thesaurus.maximus.lan
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
