// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "#### RESTFUL THESAURUS API\n",
    "title": "Thesaurus API",
    "version": "1.0.0"
  },
  "host": "thesaurus.maximus.lan",
  "basePath": "/",
  "paths": {
    "/documents": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Document"
        ],
        "summary": "Коллекция документов",
        "operationId": "documentCollection",
        "parameters": [
          {
            "$ref": "#/parameters/type.req"
          },
          {
            "$ref": "#/parameters/locale.req"
          },
          {
            "$ref": "#/parameters/code"
          },
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/offset"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/Document_response_200"
          },
          "404": {
            "$ref": "#/responses/Base_response_404"
          },
          "405": {
            "$ref": "#/responses/Base_response_405"
          },
          "500": {
            "$ref": "#/responses/Base_response_500"
          }
        }
      },
      "put": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Document"
        ],
        "summary": "Редактирование документа",
        "operationId": "documentUpdate",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Document_param"
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/Document_response_200"
          },
          "400": {
            "$ref": "#/responses/Document_response_400"
          },
          "404": {
            "$ref": "#/responses/Base_response_404"
          },
          "405": {
            "$ref": "#/responses/Base_response_405"
          },
          "500": {
            "$ref": "#/responses/Base_response_500"
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Document"
        ],
        "summary": "Создание документа",
        "operationId": "documentCreate",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Document_param"
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/Document_response_200"
          },
          "400": {
            "$ref": "#/responses/Document_response_400"
          },
          "404": {
            "$ref": "#/responses/Base_response_404"
          },
          "405": {
            "$ref": "#/responses/Base_response_405"
          },
          "500": {
            "$ref": "#/responses/Base_response_500"
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Document"
        ],
        "summary": "Удаление документа",
        "operationId": "documentDelete",
        "parameters": [
          {
            "$ref": "#/parameters/type.req"
          },
          {
            "$ref": "#/parameters/locale"
          },
          {
            "$ref": "#/parameters/code"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/Base_response_200"
          },
          "404": {
            "$ref": "#/responses/Base_response_404"
          },
          "405": {
            "$ref": "#/responses/Base_response_405"
          },
          "500": {
            "$ref": "#/responses/Base_response_500"
          }
        }
      }
    },
    "/status": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Status"
        ],
        "summary": "Статус инстанса",
        "operationId": "statusView",
        "responses": {
          "200": {
            "$ref": "#/responses/Status_response_200"
          },
          "405": {
            "$ref": "#/responses/Base_response_405"
          },
          "500": {
            "$ref": "#/responses/Base_response_500"
          }
        }
      }
    }
  },
  "definitions": {
    "Base_data": {
      "description": "Возвращает статус ответа",
      "type": "object",
      "required": [
        "version"
      ],
      "properties": {
        "version": {
          "description": "Версия ответа сервиса",
          "type": "string",
          "example": "1.0.0"
        }
      }
    },
    "Document_400_data": {
      "description": "Ошибка валидации",
      "allOf": [
        {
          "$ref": "#/definitions/Error_data"
        },
        {
          "type": "object",
          "title": "Error_400_data",
          "properties": {
            "errors": {
              "type": "object",
              "properties": {
                "core": {
                  "type": "string"
                },
                "json": {
                  "type": "string"
                },
                "validation": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "description": "Кодификатор записи",
                      "type": "string",
                      "enum": [
                        "required",
                        "string"
                      ],
                      "example": "string"
                    },
                    "locale": {
                      "description": "Локаль справочника",
                      "type": "string",
                      "enum": [
                        "required",
                        "string"
                      ],
                      "example": "required"
                    },
                    "text": {
                      "description": "Содержание записи",
                      "type": "string",
                      "enum": [
                        "required",
                        "string"
                      ],
                      "example": "string"
                    },
                    "type": {
                      "description": "Тип справочника",
                      "type": "string",
                      "enum": [
                        "required",
                        "string"
                      ],
                      "example": "required"
                    }
                  }
                }
              }
            },
            "message": {
              "type": "string",
              "example": "Authentication failure"
            }
          }
        }
      ]
    },
    "Document_param": {
      "type": "object",
      "title": "Locale_param",
      "required": [
        "type",
        "locale",
        "code",
        "text"
      ],
      "properties": {
        "code": {
          "description": "Идентификатор записи",
          "type": "string",
          "example": "MALE"
        },
        "locale": {
          "description": "Локаль справочника ISO 639-2",
          "type": "string",
          "example": "RUS"
        },
        "text": {
          "description": "Содержание записи",
          "type": "string",
          "example": "M"
        },
        "type": {
          "description": "Тип справочника",
          "type": "string",
          "example": "patient.gender"
        }
      },
      "additionalProperties": true
    },
    "Error_400_data": {
      "allOf": [
        {
          "$ref": "#/definitions/Error_data"
        },
        {
          "type": "object",
          "title": "Error_Error_400_data",
          "required": [
            "message",
            "errors"
          ],
          "properties": {
            "errors": {
              "type": "array",
              "items": {}
            },
            "message": {
              "type": "string",
              "example": "Validation error"
            }
          }
        }
      ]
    },
    "Error_404_data": {
      "allOf": [
        {
          "$ref": "#/definitions/Error_data"
        },
        {
          "type": "object",
          "title": "Error_Error_404_data",
          "required": [
            "message",
            "errors"
          ],
          "properties": {
            "errors": {
              "type": "array",
              "items": {}
            },
            "message": {
              "description": "сообщение ответа",
              "type": "string",
              "example": "Entity not found"
            }
          }
        }
      ]
    },
    "Error_405_data": {
      "allOf": [
        {
          "$ref": "#/definitions/Error_data"
        },
        {
          "type": "object",
          "title": "Error_Error_405_data",
          "properties": {
            "errors": {},
            "message": {
              "description": "сообщение ответа",
              "type": "string",
              "example": "Method ${METHOD} not allowed"
            }
          }
        }
      ]
    },
    "Error_500_data": {
      "allOf": [
        {
          "$ref": "#/definitions/Error_data"
        },
        {
          "type": "object",
          "title": "Error_Error_500_data",
          "required": [
            "message",
            "errors"
          ],
          "properties": {
            "errors": {},
            "message": {
              "description": "сообщение ответа",
              "type": "string",
              "example": "Internal server error"
            }
          }
        }
      ]
    },
    "Error_data": {
      "description": "Все плохо",
      "allOf": [
        {
          "$ref": "#/definitions/Base_data"
        },
        {
          "type": "object",
          "title": "Error_data",
          "required": [
            "data"
          ],
          "properties": {
            "data": {}
          }
        }
      ]
    },
    "Status_object": {
      "title": "Status_object",
      "properties": {
        "locales": {
          "description": "Коллекция доступных локализаций ISO 639-2",
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "RUS",
            "ENG",
            "FRA"
          ]
        },
        "name": {
          "description": "Коллекция справочника",
          "type": "string",
          "example": "patient.genders"
        },
        "type": {
          "description": "Тип справочника",
          "type": "string",
          "enum": [
            "STATIC",
            "DYNAMIC"
          ],
          "example": "STATIC"
        },
        "updated": {
          "description": "ISO8601 Дата обновления спрвочника",
          "type": "string",
          "example": "2005-08-09T18:31:42+03:30"
        }
      }
    },
    "Success_data": {
      "description": "Все хорошо",
      "allOf": [
        {
          "$ref": "#/definitions/Base_data"
        },
        {
          "type": "object",
          "title": "Success_data",
          "required": [
            "message",
            "errors"
          ],
          "properties": {
            "errors": {
              "type": "array",
              "items": {}
            },
            "message": {
              "description": "сообщение ответа",
              "type": "string",
              "example": "SUCCESS"
            }
          }
        }
      ]
    }
  },
  "parameters": {
    "code": {
      "type": "string",
      "description": "Идентфикатор документа",
      "name": "code",
      "in": "query"
    },
    "code.req": {
      "type": "string",
      "description": "Идентфикатор документа",
      "name": "code",
      "in": "query",
      "required": true
    },
    "limit": {
      "type": "integer",
      "default": 0,
      "description": "Лимит",
      "name": "limit",
      "in": "query"
    },
    "locale": {
      "type": "string",
      "description": "Локаль справочника",
      "name": "locale",
      "in": "query"
    },
    "locale.req": {
      "type": "string",
      "description": "Локаль справочника",
      "name": "locale",
      "in": "query",
      "required": true
    },
    "offset": {
      "type": "integer",
      "default": 0,
      "description": "Шаг",
      "name": "offset",
      "in": "query"
    },
    "type.req": {
      "type": "string",
      "description": "Категория документов",
      "name": "type",
      "in": "query",
      "required": true
    }
  },
  "responses": {
    "Base_response_200": {
      "description": "SUCCESS",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Success_data"
          },
          {
            "type": "object",
            "required": [
              "data"
            ],
            "properties": {
              "data": {
                "type": "array",
                "items": {}
              }
            }
          }
        ]
      }
    },
    "Base_response_400": {
      "description": "Ошибка валидации",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_400_data"
          },
          {
            "type": "object",
            "required": [
              "message",
              "errors"
            ],
            "properties": {
              "errors": {
                "type": "object",
                "properties": {
                  "core": {
                    "type": "string"
                  },
                  "json": {
                    "type": "string"
                  },
                  "validation": {
                    "type": "object"
                  }
                }
              },
              "message": {
                "type": "string",
                "example": "Authentication failure"
              }
            }
          }
        ]
      }
    },
    "Base_response_404": {
      "description": "Not found",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_404_data"
          }
        ]
      }
    },
    "Base_response_405": {
      "description": "Invalid Method",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_405_data"
          }
        ]
      }
    },
    "Base_response_500": {
      "description": "Internal server error",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_500_data"
          }
        ]
      }
    },
    "Document_response_200": {
      "description": "Справочник",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Success_data"
          },
          {
            "type": "object",
            "required": [
              "data"
            ],
            "properties": {
              "data": {
                "type": "array",
                "items": {
                  "allOf": [
                    {
                      "$ref": "#/definitions/Document_param"
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "Document_response_400": {
      "description": "Validation error",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Document_400_data"
          }
        ]
      }
    },
    "Status_response_200": {
      "description": "Объект информации об инстансе",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Success_data"
          },
          {
            "type": "object",
            "required": [
              "data"
            ],
            "properties": {
              "data": {
                "type": "array",
                "items": {
                  "allOf": [
                    {
                      "$ref": "#/definitions/Status_object"
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "#### RESTFUL THESAURUS API\n",
    "title": "Thesaurus API",
    "version": "1.0.0"
  },
  "host": "thesaurus.maximus.lan",
  "basePath": "/",
  "paths": {
    "/documents": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Document"
        ],
        "summary": "Коллекция документов",
        "operationId": "documentCollection",
        "parameters": [
          {
            "type": "string",
            "description": "Категория документов",
            "name": "type",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "Локаль справочника",
            "name": "locale",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "Идентфикатор документа",
            "name": "code",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 0,
            "description": "Лимит",
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 0,
            "description": "Шаг",
            "name": "offset",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Справочник",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Success_data"
                },
                {
                  "type": "object",
                  "required": [
                    "data"
                  ],
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "allOf": [
                          {
                            "$ref": "#/definitions/Document_param"
                          }
                        ]
                      }
                    }
                  }
                }
              ]
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Error_404_data"
                }
              ]
            }
          },
          "405": {
            "description": "Invalid Method",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Error_405_data"
                }
              ]
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Error_500_data"
                }
              ]
            }
          }
        }
      },
      "put": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Document"
        ],
        "summary": "Редактирование документа",
        "operationId": "documentUpdate",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Document_param"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Справочник",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Success_data"
                },
                {
                  "type": "object",
                  "required": [
                    "data"
                  ],
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "allOf": [
                          {
                            "$ref": "#/definitions/Document_param"
                          }
                        ]
                      }
                    }
                  }
                }
              ]
            }
          },
          "400": {
            "description": "Validation error",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Document_400_data"
                }
              ]
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Error_404_data"
                }
              ]
            }
          },
          "405": {
            "description": "Invalid Method",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Error_405_data"
                }
              ]
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Error_500_data"
                }
              ]
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Document"
        ],
        "summary": "Создание документа",
        "operationId": "documentCreate",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Document_param"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Справочник",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Success_data"
                },
                {
                  "type": "object",
                  "required": [
                    "data"
                  ],
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "allOf": [
                          {
                            "$ref": "#/definitions/Document_param"
                          }
                        ]
                      }
                    }
                  }
                }
              ]
            }
          },
          "400": {
            "description": "Validation error",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Document_400_data"
                }
              ]
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Error_404_data"
                }
              ]
            }
          },
          "405": {
            "description": "Invalid Method",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Error_405_data"
                }
              ]
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Error_500_data"
                }
              ]
            }
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Document"
        ],
        "summary": "Удаление документа",
        "operationId": "documentDelete",
        "parameters": [
          {
            "type": "string",
            "description": "Категория документов",
            "name": "type",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "Локаль справочника",
            "name": "locale",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Идентфикатор документа",
            "name": "code",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "SUCCESS",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Success_data"
                },
                {
                  "type": "object",
                  "required": [
                    "data"
                  ],
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {}
                    }
                  }
                }
              ]
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Error_404_data"
                }
              ]
            }
          },
          "405": {
            "description": "Invalid Method",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Error_405_data"
                }
              ]
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Error_500_data"
                }
              ]
            }
          }
        }
      }
    },
    "/status": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Status"
        ],
        "summary": "Статус инстанса",
        "operationId": "statusView",
        "responses": {
          "200": {
            "description": "Объект информации об инстансе",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Success_data"
                },
                {
                  "type": "object",
                  "required": [
                    "data"
                  ],
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "allOf": [
                          {
                            "$ref": "#/definitions/Status_object"
                          }
                        ]
                      }
                    }
                  }
                }
              ]
            }
          },
          "405": {
            "description": "Invalid Method",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Error_405_data"
                }
              ]
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/Error_500_data"
                }
              ]
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Base_data": {
      "description": "Возвращает статус ответа",
      "type": "object",
      "required": [
        "version"
      ],
      "properties": {
        "version": {
          "description": "Версия ответа сервиса",
          "type": "string",
          "example": "1.0.0"
        }
      }
    },
    "Document_400_data": {
      "description": "Ошибка валидации",
      "allOf": [
        {
          "$ref": "#/definitions/Error_data"
        },
        {
          "type": "object",
          "title": "Error_400_data",
          "properties": {
            "errors": {
              "type": "object",
              "properties": {
                "core": {
                  "type": "string"
                },
                "json": {
                  "type": "string"
                },
                "validation": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "description": "Кодификатор записи",
                      "type": "string",
                      "enum": [
                        "required",
                        "string"
                      ],
                      "example": "string"
                    },
                    "locale": {
                      "description": "Локаль справочника",
                      "type": "string",
                      "enum": [
                        "required",
                        "string"
                      ],
                      "example": "required"
                    },
                    "text": {
                      "description": "Содержание записи",
                      "type": "string",
                      "enum": [
                        "required",
                        "string"
                      ],
                      "example": "string"
                    },
                    "type": {
                      "description": "Тип справочника",
                      "type": "string",
                      "enum": [
                        "required",
                        "string"
                      ],
                      "example": "required"
                    }
                  }
                }
              }
            },
            "message": {
              "type": "string",
              "example": "Authentication failure"
            }
          }
        }
      ]
    },
    "Document_param": {
      "type": "object",
      "title": "Locale_param",
      "required": [
        "type",
        "locale",
        "code",
        "text"
      ],
      "properties": {
        "code": {
          "description": "Идентификатор записи",
          "type": "string",
          "example": "MALE"
        },
        "locale": {
          "description": "Локаль справочника ISO 639-2",
          "type": "string",
          "example": "RUS"
        },
        "text": {
          "description": "Содержание записи",
          "type": "string",
          "example": "M"
        },
        "type": {
          "description": "Тип справочника",
          "type": "string",
          "example": "patient.gender"
        }
      },
      "additionalProperties": true
    },
    "Error_400_data": {
      "allOf": [
        {
          "$ref": "#/definitions/Error_data"
        },
        {
          "type": "object",
          "title": "Error_Error_400_data",
          "required": [
            "message",
            "errors"
          ],
          "properties": {
            "errors": {
              "type": "array",
              "items": {}
            },
            "message": {
              "type": "string",
              "example": "Validation error"
            }
          }
        }
      ]
    },
    "Error_404_data": {
      "allOf": [
        {
          "$ref": "#/definitions/Error_data"
        },
        {
          "type": "object",
          "title": "Error_Error_404_data",
          "required": [
            "message",
            "errors"
          ],
          "properties": {
            "errors": {
              "type": "array",
              "items": {}
            },
            "message": {
              "description": "сообщение ответа",
              "type": "string",
              "example": "Entity not found"
            }
          }
        }
      ]
    },
    "Error_405_data": {
      "allOf": [
        {
          "$ref": "#/definitions/Error_data"
        },
        {
          "type": "object",
          "title": "Error_Error_405_data",
          "properties": {
            "errors": {},
            "message": {
              "description": "сообщение ответа",
              "type": "string",
              "example": "Method ${METHOD} not allowed"
            }
          }
        }
      ]
    },
    "Error_500_data": {
      "allOf": [
        {
          "$ref": "#/definitions/Error_data"
        },
        {
          "type": "object",
          "title": "Error_Error_500_data",
          "required": [
            "message",
            "errors"
          ],
          "properties": {
            "errors": {},
            "message": {
              "description": "сообщение ответа",
              "type": "string",
              "example": "Internal server error"
            }
          }
        }
      ]
    },
    "Error_data": {
      "description": "Все плохо",
      "allOf": [
        {
          "$ref": "#/definitions/Base_data"
        },
        {
          "type": "object",
          "title": "Error_data",
          "required": [
            "data"
          ],
          "properties": {
            "data": {}
          }
        }
      ]
    },
    "Status_object": {
      "title": "Status_object",
      "properties": {
        "locales": {
          "description": "Коллекция доступных локализаций ISO 639-2",
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "RUS",
            "ENG",
            "FRA"
          ]
        },
        "name": {
          "description": "Коллекция справочника",
          "type": "string",
          "example": "patient.genders"
        },
        "type": {
          "description": "Тип справочника",
          "type": "string",
          "enum": [
            "STATIC",
            "DYNAMIC"
          ],
          "example": "STATIC"
        },
        "updated": {
          "description": "ISO8601 Дата обновления спрвочника",
          "type": "string",
          "example": "2005-08-09T18:31:42+03:30"
        }
      }
    },
    "Success_data": {
      "description": "Все хорошо",
      "allOf": [
        {
          "$ref": "#/definitions/Base_data"
        },
        {
          "type": "object",
          "title": "Success_data",
          "required": [
            "message",
            "errors"
          ],
          "properties": {
            "errors": {
              "type": "array",
              "items": {}
            },
            "message": {
              "description": "сообщение ответа",
              "type": "string",
              "example": "SUCCESS"
            }
          }
        }
      ]
    }
  },
  "parameters": {
    "code": {
      "type": "string",
      "description": "Идентфикатор документа",
      "name": "code",
      "in": "query"
    },
    "code.req": {
      "type": "string",
      "description": "Идентфикатор документа",
      "name": "code",
      "in": "query",
      "required": true
    },
    "limit": {
      "type": "integer",
      "default": 0,
      "description": "Лимит",
      "name": "limit",
      "in": "query"
    },
    "locale": {
      "type": "string",
      "description": "Локаль справочника",
      "name": "locale",
      "in": "query"
    },
    "locale.req": {
      "type": "string",
      "description": "Локаль справочника",
      "name": "locale",
      "in": "query",
      "required": true
    },
    "offset": {
      "type": "integer",
      "default": 0,
      "description": "Шаг",
      "name": "offset",
      "in": "query"
    },
    "type.req": {
      "type": "string",
      "description": "Категория документов",
      "name": "type",
      "in": "query",
      "required": true
    }
  },
  "responses": {
    "Base_response_200": {
      "description": "SUCCESS",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Success_data"
          },
          {
            "type": "object",
            "required": [
              "data"
            ],
            "properties": {
              "data": {
                "type": "array",
                "items": {}
              }
            }
          }
        ]
      }
    },
    "Base_response_400": {
      "description": "Ошибка валидации",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_400_data"
          },
          {
            "type": "object",
            "required": [
              "message",
              "errors"
            ],
            "properties": {
              "errors": {
                "type": "object",
                "properties": {
                  "core": {
                    "type": "string"
                  },
                  "json": {
                    "type": "string"
                  },
                  "validation": {
                    "type": "object"
                  }
                }
              },
              "message": {
                "type": "string",
                "example": "Authentication failure"
              }
            }
          }
        ]
      }
    },
    "Base_response_404": {
      "description": "Not found",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_404_data"
          }
        ]
      }
    },
    "Base_response_405": {
      "description": "Invalid Method",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_405_data"
          }
        ]
      }
    },
    "Base_response_500": {
      "description": "Internal server error",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_500_data"
          }
        ]
      }
    },
    "Document_response_200": {
      "description": "Справочник",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Success_data"
          },
          {
            "type": "object",
            "required": [
              "data"
            ],
            "properties": {
              "data": {
                "type": "array",
                "items": {
                  "allOf": [
                    {
                      "$ref": "#/definitions/Document_param"
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "Document_response_400": {
      "description": "Validation error",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Document_400_data"
          }
        ]
      }
    },
    "Status_response_200": {
      "description": "Объект информации об инстансе",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Success_data"
          },
          {
            "type": "object",
            "required": [
              "data"
            ],
            "properties": {
              "data": {
                "type": "array",
                "items": {
                  "allOf": [
                    {
                      "$ref": "#/definitions/Status_object"
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}`))
}
