// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DocumentCreateOKCode is the HTTP code returned for type DocumentCreateOK
const DocumentCreateOKCode int = 200

/*DocumentCreateOK Справочник

swagger:response documentCreateOK
*/
type DocumentCreateOK struct {

	/*
	  In: Body
	*/
	Payload *DocumentCreateOKBody `json:"body,omitempty"`
}

// NewDocumentCreateOK creates DocumentCreateOK with default headers values
func NewDocumentCreateOK() *DocumentCreateOK {

	return &DocumentCreateOK{}
}

// WithPayload adds the payload to the document create o k response
func (o *DocumentCreateOK) WithPayload(payload *DocumentCreateOKBody) *DocumentCreateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the document create o k response
func (o *DocumentCreateOK) SetPayload(payload *DocumentCreateOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DocumentCreateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DocumentCreateBadRequestCode is the HTTP code returned for type DocumentCreateBadRequest
const DocumentCreateBadRequestCode int = 400

/*DocumentCreateBadRequest Validation error

swagger:response documentCreateBadRequest
*/
type DocumentCreateBadRequest struct {

	/*
	  In: Body
	*/
	Payload *DocumentCreateBadRequestBody `json:"body,omitempty"`
}

// NewDocumentCreateBadRequest creates DocumentCreateBadRequest with default headers values
func NewDocumentCreateBadRequest() *DocumentCreateBadRequest {

	return &DocumentCreateBadRequest{}
}

// WithPayload adds the payload to the document create bad request response
func (o *DocumentCreateBadRequest) WithPayload(payload *DocumentCreateBadRequestBody) *DocumentCreateBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the document create bad request response
func (o *DocumentCreateBadRequest) SetPayload(payload *DocumentCreateBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DocumentCreateBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DocumentCreateNotFoundCode is the HTTP code returned for type DocumentCreateNotFound
const DocumentCreateNotFoundCode int = 404

/*DocumentCreateNotFound Not found

swagger:response documentCreateNotFound
*/
type DocumentCreateNotFound struct {

	/*
	  In: Body
	*/
	Payload *DocumentCreateNotFoundBody `json:"body,omitempty"`
}

// NewDocumentCreateNotFound creates DocumentCreateNotFound with default headers values
func NewDocumentCreateNotFound() *DocumentCreateNotFound {

	return &DocumentCreateNotFound{}
}

// WithPayload adds the payload to the document create not found response
func (o *DocumentCreateNotFound) WithPayload(payload *DocumentCreateNotFoundBody) *DocumentCreateNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the document create not found response
func (o *DocumentCreateNotFound) SetPayload(payload *DocumentCreateNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DocumentCreateNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DocumentCreateMethodNotAllowedCode is the HTTP code returned for type DocumentCreateMethodNotAllowed
const DocumentCreateMethodNotAllowedCode int = 405

/*DocumentCreateMethodNotAllowed Invalid Method

swagger:response documentCreateMethodNotAllowed
*/
type DocumentCreateMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *DocumentCreateMethodNotAllowedBody `json:"body,omitempty"`
}

// NewDocumentCreateMethodNotAllowed creates DocumentCreateMethodNotAllowed with default headers values
func NewDocumentCreateMethodNotAllowed() *DocumentCreateMethodNotAllowed {

	return &DocumentCreateMethodNotAllowed{}
}

// WithPayload adds the payload to the document create method not allowed response
func (o *DocumentCreateMethodNotAllowed) WithPayload(payload *DocumentCreateMethodNotAllowedBody) *DocumentCreateMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the document create method not allowed response
func (o *DocumentCreateMethodNotAllowed) SetPayload(payload *DocumentCreateMethodNotAllowedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DocumentCreateMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DocumentCreateInternalServerErrorCode is the HTTP code returned for type DocumentCreateInternalServerError
const DocumentCreateInternalServerErrorCode int = 500

/*DocumentCreateInternalServerError Internal server error

swagger:response documentCreateInternalServerError
*/
type DocumentCreateInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *DocumentCreateInternalServerErrorBody `json:"body,omitempty"`
}

// NewDocumentCreateInternalServerError creates DocumentCreateInternalServerError with default headers values
func NewDocumentCreateInternalServerError() *DocumentCreateInternalServerError {

	return &DocumentCreateInternalServerError{}
}

// WithPayload adds the payload to the document create internal server error response
func (o *DocumentCreateInternalServerError) WithPayload(payload *DocumentCreateInternalServerErrorBody) *DocumentCreateInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the document create internal server error response
func (o *DocumentCreateInternalServerError) SetPayload(payload *DocumentCreateInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DocumentCreateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
